[project]
name = "tabswitch"
version = "0.0.1"
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
  "requests",
]

[project.scripts]
tabswitch = "tabswitch:main"

[tool.black]
target-version = ["py310"]
